.github/workflows/pr-issue-validator.yaml
adds pull request validation
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1362
adds missing labels
=> feat: Create pr-issue-validator.yaml

ci-runner/executor/StageExecutor.go, ci-runner/executor/util/envUtils.go
fix: ref plugin variables get overriden through recursive call
=> chore: ref plugin variables get overriden through recursive call

common-lib/utils/k8s/K8sUtil.go
fixes https://github.com/devtron-labs/sprint-tasks/issues/1543
=> misc: added more log for checking if ns exists or not

.github/semantic.yml, .github/workflows/pr-issue-validator.yaml
1. added sync to semantic.yaml and pr validator
2. removed issue status dependency in pr-validator
=> misc: remove issue status for pr validation

ci-runner/executor/StageExecutor.go, ci-runner/executor/stage/cdStages.go, ci-runner/executor/stage/ciStages.go, ci-runner/executor/util/envUtils.go
issue - https://github.com/orgs/devtron-labs/projects/4/views/3?pane=issue&itemId=92332973&issue=devtron-labs%7Csprint-tasks%7C1635
=> misc: variable override in pre/ post stage

.github/workflows/pr-issue-validator.yaml, ci-runner/executor/StageExecutor.go, ci-runner/executor/stage/cdStages.go, ci-runner/executor/stage/ciStages.go, ci-runner/executor/util/envUtils.go
Fixes: https://github.com/devtron-labs/sprint-tasks/issues/1635
=> misc: stage variable values gets override by value given in first stage

image-scanner/pkg/middleware/instrument.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1587
=> fix: remove unused variable

.github/workflows/pr-issue-validator.yaml, ci-runner/executor/stage/cdStages.go, ci-runner/executor/stage/ciStages.go, ci-runner/helper/EventHelper.go, ci-runner/helper/adaptor/CiStageAdaptor.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1852
Auto triggerred even if pre-cd fails
=> fix: Auto triggerred even if pre-cd fails

ci-runner/executor/stage/ciStages.go, ci-runner/helper/DockerHelper.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1650
=> fix: Container push avoid

chart-sync/go.mod, chart-sync/go.sum, chart-sync/vendor/modules.txt, ci-runner/executor/StageExecutor_test.go, ci-runner/executor/scriptExecutor.go, ci-runner/executor/scriptExecutor_test.go, ci-runner/go.mod, ci-runner/go.sum, ci-runner/vendor/modules.txt, git-sensor/go.mod, git-sensor/go.sum, git-sensor/vendor/modules.txt, image-scanner/go.mod, image-scanner/go.sum, image-scanner/vendor/modules.txt, kubelink/go.mod, kubelink/go.sum, kubelink/vendor/modules.txt, kubewatch/go.mod, kubewatch/go.sum, kubewatch/vendor/modules.txt, lens/go.mod, lens/go.sum, lens/vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1908
=> fix: multi line variable support for docker run cmd

chart-sync/go.mod, chart-sync/go.sum, chart-sync/vendor/modules.txt, ci-runner/executor/StageExecutor_test.go, ci-runner/executor/scriptExecutor.go, ci-runner/executor/scriptExecutor_test.go, ci-runner/go.mod, ci-runner/go.sum, ci-runner/vendor/modules.txt, git-sensor/go.mod, git-sensor/go.sum, git-sensor/vendor/modules.txt, image-scanner/go.mod, image-scanner/go.sum, image-scanner/vendor/modules.txt, kubelink/go.mod, kubelink/go.sum, kubelink/vendor/modules.txt, kubewatch/go.mod, kubewatch/go.sum, kubewatch/vendor/modules.txt, lens/go.mod, lens/go.sum, lens/vendor/modules.txt
Reverts devtron-labs/devtron-services#145
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1908
=> Revert "fix: multi line variable support for docker run cmd"

chart-sync/go.mod, chart-sync/go.sum, chart-sync/vendor/modules.txt, ci-runner/go.mod, ci-runner/go.sum, ci-runner/vendor/modules.txt, git-sensor/go.mod, git-sensor/go.sum, git-sensor/vendor/modules.txt, image-scanner/go.mod, image-scanner/go.sum, image-scanner/pkg/security/ImageScanService.go, image-scanner/vendor/modules.txt, kubelink/go.mod, kubelink/go.sum, kubelink/vendor/modules.txt, kubewatch/go.mod, kubewatch/go.sum, kubewatch/vendor/modules.txt, lens/go.mod, lens/go.sum, lens/vendor/modules.txt
Fix: https://github.com/devtron-labs/sprint-tasks/issues/1824
=> fix: image scan fixes

git-sensor/Dockerfile
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1824
=> fix: Dockerfile dir fix

chart-sync/go.mod, chart-sync/go.sum, chart-sync/vendor/modules.txt, ci-runner/go.mod, ci-runner/go.sum, ci-runner/vendor/modules.txt, git-sensor/go.mod, git-sensor/go.sum, git-sensor/vendor/modules.txt, image-scanner/go.mod, image-scanner/go.sum, image-scanner/vendor/modules.txt, kubelink/go.mod, kubelink/go.sum, kubelink/pkg/service/helmApplicationService/helmAppService.go, kubelink/vendor/modules.txt, kubewatch/go.mod, kubewatch/go.sum, kubewatch/vendor/modules.txt, lens/go.mod, lens/go.sum, lens/vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1826
Revert
=> fix: "revert: charts template fix (#163)"

chart-sync/go.mod, chart-sync/go.sum, chart-sync/vendor/modules.txt, ci-runner/go.mod, ci-runner/go.sum, ci-runner/vendor/modules.txt, git-sensor/go.mod, git-sensor/go.sum, git-sensor/vendor/modules.txt, image-scanner/go.mod, image-scanner/go.sum, image-scanner/vendor/modules.txt, kubelink/go.mod, kubelink/go.sum, kubelink/pkg/service/helmApplicationService/helmAppService.go, kubelink/vendor/modules.txt, kubewatch/go.mod, kubewatch/go.sum, kubewatch/vendor/modules.txt, lens/go.mod, lens/go.sum, lens/vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1826
=> fix: Revert "charts template fix"

chart-sync/go.mod, chart-sync/go.sum, chart-sync/vendor/modules.txt, ci-runner/go.mod, ci-runner/go.sum, ci-runner/vendor/modules.txt, common-lib/utils/k8s/K8sUtil.go, common-lib/utils/k8s/K8sUtil_test.go, git-sensor/go.mod, git-sensor/go.sum, git-sensor/vendor/modules.txt, image-scanner/go.mod, image-scanner/go.sum, image-scanner/vendor/modules.txt, kubelink/go.mod, kubelink/go.sum, kubelink/vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go, kubelink/vendor/modules.txt, kubelink/wire_gen.go, kubewatch/go.mod, kubewatch/go.sum, kubewatch/vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go, kubewatch/vendor/modules.txt, lens/go.mod, lens/go.sum, lens/vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1939
=> fix: fix for when user is unrecognisable, then kubelink restarts with panic due to k8sService is assigned nil

kubewatch/pkg/informer/cluster/systemExec/helper.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1819
=> fix: fix for wrong ci status for node eviction cases

git-sensor/pkg/git/GitCliManager.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1980
=> fix: git cli author 

git-sensor/pkg/git/GitCliManager.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1980
=> fix: git cli author

chart-sync/go.mod, chart-sync/go.sum, chart-sync/vendor/modules.txt, ci-runner/go.mod, ci-runner/go.sum, ci-runner/vendor/modules.txt, git-sensor/go.mod, git-sensor/go.sum, git-sensor/internals/sql/CiPipelineMaterial.go, git-sensor/pkg/RepoManages.go, git-sensor/pkg/git/RepositoryManager.go, git-sensor/pkg/git/Watcher.go, git-sensor/vendor/modules.txt, image-scanner/go.mod, image-scanner/go.sum, image-scanner/vendor/modules.txt, kubelink/go.mod, kubelink/go.sum, kubelink/vendor/modules.txt, kubewatch/go.mod, kubewatch/go.sum, kubewatch/vendor/modules.txt, lens/go.mod, lens/go.sum, lens/vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1810
=> fix: error handling for git material

chart-sync/go.mod, chart-sync/go.sum, chart-sync/vendor/modules.txt, ci-runner/executor/stage/ciStages.go, ci-runner/go.mod, ci-runner/go.sum, ci-runner/vendor/modules.txt, git-sensor/go.mod, git-sensor/go.sum, git-sensor/vendor/modules.txt, image-scanner/go.mod, image-scanner/go.sum, image-scanner/vendor/modules.txt, kubelink/go.mod, kubelink/go.sum, kubelink/vendor/modules.txt, kubewatch/go.mod, kubewatch/go.sum, kubewatch/vendor/modules.txt, lens/go.mod, lens/go.sum, lens/vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1831
=> fix: panic handling for build pack

chart-sync/go.mod, chart-sync/go.sum, chart-sync/vendor/modules.txt, ci-runner/Dockerfile, ci-runner/go.mod, ci-runner/go.sum, ci-runner/vendor/github.com/devtron-labs/common-lib/blob-storage/AwsS3Blob.go, ci-runner/vendor/github.com/devtron-labs/common-lib/blob-storage/BlobUtils.go, ci-runner/vendor/modules.txt, common-lib/blob-storage/AwsS3Blob.go, common-lib/blob-storage/BlobUtils.go, git-sensor/go.mod, git-sensor/go.sum, git-sensor/vendor/modules.txt, image-scanner/go.mod, image-scanner/go.sum, image-scanner/vendor/modules.txt, kubelink/go.mod, kubelink/go.sum, kubelink/vendor/modules.txt, kubewatch/go.mod, kubewatch/go.sum, kubewatch/vendor/modules.txt, lens/go.mod, lens/go.sum, lens/vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2095
=> fix: S3 default integrity change

chart-sync/go.mod, chart-sync/go.sum, chart-sync/vendor/modules.txt, ci-runner/go.mod, ci-runner/go.sum, ci-runner/helper/DockerHelper.go, ci-runner/vendor/modules.txt, git-sensor/go.mod, git-sensor/go.sum, git-sensor/vendor/modules.txt, image-scanner/go.mod, image-scanner/go.sum, image-scanner/vendor/modules.txt, kubelink/go.mod, kubelink/go.sum, kubelink/vendor/modules.txt, kubewatch/go.mod, kubewatch/go.sum, kubewatch/vendor/modules.txt, lens/go.mod, lens/go.sum, lens/vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2168
=> fix: docker login is not executed for pre/post cd stage executions

chart-sync/go.mod, chart-sync/go.sum, chart-sync/vendor/modules.txt, ci-runner/executor/StageExecutor.go, ci-runner/executor/scriptExecutor.go, ci-runner/go.mod, ci-runner/go.sum, ci-runner/vendor/github.com/devtron-labs/common-lib/workflow/bean.go, ci-runner/vendor/modules.txt, common-lib/utils/k8s/commonBean/bean.go, common-lib/workflow/bean.go, git-sensor/go.mod, git-sensor/go.sum, git-sensor/vendor/modules.txt, image-scanner/go.mod, image-scanner/go.sum, image-scanner/vendor/modules.txt, kubelink/go.mod, kubelink/go.sum, kubelink/vendor/github.com/devtron-labs/common-lib/utils/k8s/commonBean/bean.go, kubelink/vendor/modules.txt, kubewatch/go.mod, kubewatch/go.sum, kubewatch/vendor/github.com/devtron-labs/common-lib/utils/k8s/commonBean/bean.go, kubewatch/vendor/modules.txt, lens/go.mod, lens/go.sum, lens/vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2110
=> feat: mount file type variable in ci-runner through cm

ci-runner/helper/DockerHelper.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2190
=> fix: Docker login condition for devtron job

chart-sync/go.mod, chart-sync/go.sum, chart-sync/vendor/github.com/devtron-labs/common-lib/utils/SqlUtil.go, chart-sync/vendor/modules.txt, ci-runner/go.mod, ci-runner/go.sum, ci-runner/vendor/github.com/devtron-labs/common-lib/utils/SqlUtil.go, ci-runner/vendor/modules.txt, common-lib/utils/SqlUtil.go, git-sensor/go.mod, git-sensor/go.sum, git-sensor/vendor/github.com/devtron-labs/common-lib/utils/SqlUtil.go, git-sensor/vendor/modules.txt, image-scanner/go.mod, image-scanner/go.sum, image-scanner/vendor/github.com/devtron-labs/common-lib/utils/SqlUtil.go, image-scanner/vendor/modules.txt, kubelink/go.mod, kubelink/go.sum, kubelink/vendor/github.com/devtron-labs/common-lib/utils/SqlUtil.go, kubelink/vendor/modules.txt, kubewatch/go.mod, kubewatch/go.sum, kubewatch/vendor/github.com/devtron-labs/common-lib/utils/SqlUtil.go, kubewatch/vendor/modules.txt, lens/go.mod, lens/go.sum, lens/vendor/github.com/devtron-labs/common-lib/utils/SqlUtil.go, lens/vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2248
=> fix: Remove funtionName from labels from pg_query_duration_seconds_* metrics

.github/workflows/pr-issue-validator.yaml
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1311
=> fix: pr validator centralisation

git-sensor/pkg/git/RepositoryManager.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2427
=> fix: ssh with single commit

authenticator/client/oidcClient.go
Fixes: https://github.com/devtron-labs/sprint-tasks/issues/2572
=> fix: dex scopes override default required scopes

git-sensor/pkg/RepoManages.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2615
=> fix: reset checkout message on successful fetch
